var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-0.8504443233832717,undefined);
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1',01);
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1',01);
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1',01);
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1',01);
mock.restore();
subject.normalize('');
subject.format('','',{normalize: true});
subject.blackListNumber('');
subject.inc('','');
subject.fileTest('','',0);
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
